"""Markdown → PDF rendering for the create_pdf_report tool (PLAN.md §B5 tool 2).

Pure-Python pipeline: `markdown` (md → HTML) + `xhtml2pdf`/pisa (HTML → PDF).
Chosen over WeasyPrint deliberately — WeasyPrint needs native libpango/cairo
that are painful on the deploy host (PLAN.md pitfall #8); this path has no
system dependencies, so it works identically on the laptop and on Railway.
"""

import io

import markdown

from xhtml2pdf import pisa

# Minimal print stylesheet. xhtml2pdf supports a conservative CSS subset, so we
# keep it simple: readable serif body, tighter sans headings, wrapped code.
_CSS = """
@page { size: A4; margin: 2.2cm 2cm; }
body { font-family: Helvetica, Arial, sans-serif; font-size: 11pt; color: #1a1a1a; line-height: 1.5; }
h1 { font-size: 20pt; margin: 0 0 4pt; }
h2 { font-size: 15pt; margin: 16pt 0 4pt; }
h3 { font-size: 12.5pt; margin: 12pt 0 4pt; }
p { margin: 0 0 8pt; }
ul, ol { margin: 0 0 8pt 16pt; }
li { margin: 0 0 3pt; }
a { color: #1d4ed8; text-decoration: none; }
code { font-family: Courier, monospace; font-size: 9.5pt; background: #f3f4f6; }
pre { font-family: Courier, monospace; font-size: 9.5pt; background: #f3f4f6; padding: 8pt; }
blockquote { margin: 0 0 8pt; padding-left: 10pt; border-left: 3px solid #d1d5db; color: #4b5563; }
hr { border: none; border-top: 1px solid #e5e7eb; }
.title { font-size: 22pt; font-weight: bold; margin-bottom: 2pt; }
.subtitle { color: #6b7280; font-size: 9pt; margin-bottom: 18pt; }
"""


def render_markdown_pdf(title: str, markdown_content: str) -> bytes:
    """Render a titled markdown document to PDF bytes.

    Raises RuntimeError if pisa reports a rendering error so the caller can
    surface a clean tool error to the model rather than returning a broken file.
    """
    body_html = markdown.markdown(
        markdown_content or "",
        extensions=["extra", "sane_lists", "nl2br"],
    )
    safe_title = markdown.markdown(title or "Report").strip()
    # markdown() wraps a bare title in <p>…</p>; strip that for the heading.
    if safe_title.startswith("<p>") and safe_title.endswith("</p>"):
        safe_title = safe_title[3:-4]

    document = f"""<!DOCTYPE html>
<html><head><meta charset="utf-8"><style>{_CSS}</style></head>
<body>
  <div class="title">{safe_title}</div>
  <div class="subtitle">Generated by MicroManus</div>
  {body_html}
</body></html>"""

    buffer = io.BytesIO()
    result = pisa.CreatePDF(src=document, dest=buffer, encoding="utf-8")
    if result.err:
        raise RuntimeError("PDF rendering failed")
    return buffer.getvalue()
