"""Supabase Storage upload + signed URLs for PDF artifacts (PLAN.md §B1/§B5).

PDFs generated by create_pdf_report are uploaded to the private `artifacts`
bucket and handed back to the user as a time-limited signed URL (7 days). The
bucket is private, so the raw object path is never publicly reachable — only the
signed URL is, and only until it expires.

Human setup (one-time): Supabase dashboard → Storage → create a **private**
bucket named `artifacts`.
"""

import uuid

from app.supabase_client import get_supabase

BUCKET = "artifacts"

# Signed-URL lifetime: 7 days, per PLAN.md §B1.
SIGNED_URL_TTL_SECONDS = 7 * 24 * 60 * 60


def upload_pdf(user_id: str, data: bytes, title: str) -> str:
    """Upload PDF bytes for a user and return a 7-day signed URL.

    Objects are namespaced under the user's id (`<user_id>/<uuid>.pdf`) so a
    signed URL can't be guessed into another user's files.
    """
    supabase = get_supabase()
    path = f"{user_id}/{uuid.uuid4().hex}.pdf"

    supabase.storage.from_(BUCKET).upload(
        path,
        data,
        {"content-type": "application/pdf"},
    )

    signed = supabase.storage.from_(BUCKET).create_signed_url(
        path, SIGNED_URL_TTL_SECONDS
    )
    # supabase-py returns a dict; the key has varied across versions.
    url = signed.get("signedURL") or signed.get("signedUrl") or signed.get("signed_url")
    if not url:
        raise RuntimeError("Could not create a signed URL for the uploaded PDF")
    return url
